#ifndef SOUND_DRIVER_H
#define SOUND_DRIVER_H

// #define  	SOUND_TYPE_LOW_BAT					0X00
// #define  	SOUND_TYPE_WEAR_ABNORMAL			0X01
// #define  	SOUND_TYPE_SHOCK_START				0X02
// #define  	SOUND_TYPE_DESTROYED				0X03
// #define  	SOUND_TYPE_SINGLE_TEST				0X04
// #define  	SOUND_TYPE_SET_GROUP_SUSCESS		0X05
// #define  	SOUND_TYPE_SET_POWER_HIGH_SUCCESS	0X06
// #define  	SOUND_TYPE_SET_POWER_MID_SUCCESS	0X07
// #define  	SOUND_TYPE_SET_POWER_LOW_SUCCESS	0X08
// #define  	SOUND_TYPE_WEAR_NORMAL				0X09
// #define  	SOUND_TYPE_CLEAR_GROUP_SUSCESS		0XF0
// #define  	SOUND_TYPE_OPEN_ESCAPE				0XF1
// #define  	SOUND_TYPE_CLOSE_ESCAPE				0XF2
// #define  	SOUND_TYPE_ESCAPE_ALARM1			0XF3
// #define  	SOUND_TYPE_ESCAPE_ALARM2			0XF4
// #define  	SOUND_TYPE_CONTROL_ENABLE			0XF5
// #define  	SOUND_TYPE_CONTROL_DISABLE			0XF6
// #define  	SOUND_TYPE_SHOCK_STOP				0XF7
// #define  	SOUND_TYPE_UNLOCK					0XF8
// #define  	SOUND_TYPE_INSERT_DETECT_ENABLE		0XF9
// #define  	SOUND_TYPE_INSERT_DETECT_DISABLE	0XFA


#define  	SOUND_TYPE_LOW_BAT					0X00
#define  	SOUND_TYPE_WEAR_ABNORMAL			0X01
#define  	SOUND_TYPE_SHOCK_START				0X02
#define  	SOUND_TYPE_DESTROYED				0X03
#define  	SOUND_TYPE_SINGLE_TEST				0X04
#define  	SOUND_TYPE_SET_GROUP_SUSCESS		0X05
#define  	SOUND_TYPE_SET_POWER_HIGH_SUCCESS	0X06
#define  	SOUND_TYPE_SET_POWER_MID_SUCCESS	0X07
#define  	SOUND_TYPE_SET_POWER_LOW_SUCCESS	0X08
#define  	SOUND_TYPE_WEAR_NORMAL				0X09
#define  	SOUND_TYPE_CLEAR_GROUP_SUSCESS		0X08
#define  	SOUND_TYPE_OPEN_ESCAPE				0X08
#define  	SOUND_TYPE_CLOSE_ESCAPE				0X08
#define  	SOUND_TYPE_ESCAPE_ALARM1			0X08
#define  	SOUND_TYPE_ESCAPE_ALARM2			0X08
#define  	SOUND_TYPE_CONTROL_ENABLE			0X08
#define  	SOUND_TYPE_CONTROL_DISABLE			0X08
#define  	SOUND_TYPE_SHOCK_STOP				0X08
#define  	SOUND_TYPE_UNLOCK					0X08
#define  	SOUND_TYPE_INSERT_DETECT_ENABLE		0X08
#define  	SOUND_TYPE_INSERT_DETECT_DISABLE	0X08



#define  	SOUND_TYPE_DI					0X07
#define  	SOUND_TYPE_DI_DI				0X08
#define  	SOUND_TYPE_DI_DI_DI				0X09


#define  	SOUND_TYPE_VOLUME_MAX			0XFF

void SoundDriverInit(void);
void SoundEventSet(uint8_t event);
void SoundDriverSet(uint8_t soundType);
extern uint8_t soundEventType;


#endif //_SOUND_DRIVER_H
